# Generated by Django 2.2.3 on 2019-07-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190730_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympian',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
