# Generated by Django 2.2.3 on 2019-07-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190730_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympian',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='medal',
            field=models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
